version: '3.8'

networks:
  cabsharing_network:
    ipam:
      config:
        - subnet: 172.22.0.0/24

services:
    cabsharing:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            cabsharing_network:
                ipv4_address: 172.22.0.2
        env_file:
            - ./.env
        volumes:
            - ./sqllite_volume:/app/sqllite_volume
        tty: true
    sqliteweb:
        build:
            context: .
            dockerfile: Dockerfile-sqliteweb
        networks:
            cabsharing_network:
                ipv4_address: 172.22.0.3
        env_file:
            - ./.env
        volumes:
            - ./sqllite_volume:/app/sqllite_volume
        tty: true
    telegram-bot:
        build:
            context: .
            dockerfile: Dockerfile.telegram_bot
        container_name: cabmiloge-telegram-bot
        restart: always
        volumes:
            - ./sqllite_volume:/app/sqllite_volume
        environment:
            - TELEGRAM_BOT_TOKEN=7930956524:AAEUxigMRTX3tzLZXxz3J5UYKhyjHUj20Nk
        depends_on:
            - cabsharing