FROM python:3.9-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY telegram_bot.py .
ENV PYTHONUNBUFFERED=1
RUN mkdir -p /app/sqllite_volume
CMD ["python3", "telegram_bot.py"]